SELECT 
  AA.T_BANK AS BANKID,
  AA.T_NAME AS DISPNAME,
  NVL(SUM(DECODE(DECODE(AA.TYPE, '0', AA.TNUM, '0', '1'),'0',AMT1,0)),0) AS DEPOSIT,
  (NVL(SUM(DECODE(AA.TYPE, '0', '0', AMT1)), 0)) AS SALE_AMT,
  NVL(SUM(DECODE(AA.REVST,'0','0',DECODE(AA.TYPE,'1',AMT1,DECODE(AA.TNUM, '0', AMT1, '0')))),0) AS ETO_AMT,
  (NVL(SUM(DECODE(AA.TYPE, '0', '0', AMT1)), 0) + SUM(DECODE(DECODE(AA.TYPE, '0', AA.TNUM, '0', '1'),'0',AMT1,0))) AS SALE_TOTAL,
  (NVL(SUM(DECODE(AA.TYPE, '0', '0', AMT1)), 0) -SUM(DECODE(AA.REVST,'0','0',DECODE(AA.TYPE,'1',AMT1,DECODE(AA.TNUM, '0', AMT1, '0'))))) AS SALE_ETO,
  SUM(NVL(SUM(DECODE(DECODE(AA.TYPE, '0', AA.TNUM, '0', '1'),'0',AMT1,0)),0)) OVER() AS TOTAL_DEPOSIT,
  SUM(NVL(SUM(DECODE(AA.TYPE, '0', '0', AMT1)), 0)) OVER() AS TOTAL_SALE_AMT,
  SUM(NVL(SUM(DECODE(AA.REVST,'0','0',DECODE(AA.TYPE,'1',AMT1,DECODE(AA.TNUM, '0', AMT1, '0')))),0)) OVER() AS TOTAL_ETO_AMT,
  SUM(NVL(SUM(DECODE(AA.TYPE, '0', '0', AMT1)), 0) -SUM(DECODE(AA.REVST,'0','0',DECODE(AA.TYPE,'1',AMT1,DECODE(AA.TNUM, '0', AMT1, '0'))))) OVER() AS TOTAL_SALE_ETO,
  SUM(NVL(SUM(DECODE(AA.TYPE, '0', '0', AMT1)), 0) + SUM(DECODE(DECODE(AA.TYPE, '0', AA.TNUM, '0', '1'),'0',AMT1,0))) OVER() AS TOTAL_SALE_TOTAL
FROM (SELECT R.AMT1,
             DECODE(R.TYPE,'a7',0,'jz',0,'jc',0,'dp',0,'z1',0,1) AS TYPE,
             DECODE(R.NUM1, '0', '0', '1', '0', 1) AS TNUM,
             BANK.T_BANK,
             BANK.T_NAME,
             DECODE(R.STATUS,'4',TO_CHAR(R.CHECK_DATE, 'yyyymmdd') -NVL(R.REMARK, 0),0) AS REVST
      FROM GD_BILLHEADER R,TABLE(GOOGSWEB_PUB.GETBANKVIEW('4489900', '1')) BANK
      WHERE BANK.B_BANK = R.BANKID
      AND R.STATUS IN ('5', '3', '4')
      AND R.TRAN_STAT = '1'
      AND R.TYPE IN ('a6', 'av', 'a7', 'dh', 'j6', 'jv', 'iv', 'j7', 'jz', 'jc', 'jh', 'dp', 'z1', 'z2')
      AND (R.CHECK_DATE) >= TO_DATE('2019-07-13', 'YYYY-MM-DD')
      AND (R.CHECK_DATE) < TO_DATE('2019-08-13', 'YYYY-MM-DD') + 1
      ORDER BY BANK.B_BANKLVL) AA
GROUP BY AA.T_BANK, AA.T_NAME;
         
SELECT t.* FROM gd_billheader t WHERE t.type IN ('a7');
